%% generate_figure_sphere.m
%
% Generates Figure 4 for the PEF mathematics companion paper:
%   "eta as inverse spherical chord"
%
% Plots the 113 sports KPI studies on the unit sphere, where each KPI sits
% at (sphere_x, sphere_y, sphere_z) = (cos sigma, sin sigma cos phi,
% sin sigma sin phi) with sigma = arccos(rho sech tau).  Points are coloured
% by empirical quadrant.  Iso-eta latitude circles and the key meridians
% (Fisher line tau=0, independence equator rho=0) are overlaid.
%
% OUTPUT: figures/Figure_4_sphere.png
%
% USAGE (from pef-mathematics root):
%   /Applications/MATLAB_R2025b.app/bin/matlab -batch \
%     "cd('scripts'); run('generate_figure_sphere.m')"
%
% INPUTS: ../validation_inputs/pef_landscape_2season_geometry.csv
%         (generated by pef-empirical pipeline, synced via sync_to_companion.sh)

clear; close all; clc;

%% -------------------------------------------------------------------------
%  0. Paths
% -------------------------------------------------------------------------
repo_root  = fileparts(fileparts(mfilename('fullpath')));
csv_path   = fullfile(repo_root, 'validation_inputs', ...
                      'pef_landscape_2season_geometry.csv');
fig_dir    = fullfile(repo_root, 'figures');
if ~exist(fig_dir, 'dir'), mkdir(fig_dir); end
out_path   = fullfile(fig_dir, 'Figure_4_sphere.png');

%% -------------------------------------------------------------------------
%  1. Load KPI data
% -------------------------------------------------------------------------
T = readtable(csv_path, 'TextType', 'string');

sx = T.sphere_x;   % cos(sigma) = rho*sech(tau)
sy = T.sphere_y;   % sqrt(1 - sx^2 - sz^2), positive branch
sz = T.sphere_z;   % tanh(tau)
eta_vals  = T.eta;
quad      = T.quadrant;
sig_rho   = T.sig_rho;   % 1 if rho significant at p<0.05, else 0

%% -------------------------------------------------------------------------
%  2. Colour scheme (matches empirical paper)
%   Q1 (kappa>1, rho>0): blue    -- balanced, positive correlation
%   Q2 (kappa<1, rho>0): green   -- asymmetric, positive correlation
%   Q3 (kappa<1, rho<0): red     -- asymmetric, negative correlation
%   Q4 (kappa>1, rho<0): orange  -- balanced, negative (competitive)
% -------------------------------------------------------------------------
col_Q1 = [0.18  0.44  0.76];
col_Q2 = [0.16  0.63  0.30];
col_Q3 = [0.80  0.18  0.18];
col_Q4 = [0.93  0.55  0.12];
col_bnd = [0.50  0.50  0.50];

quad_colour = @(q) ...
    col_Q1 .* strcmp(q,'Q1') + col_Q2 .* strcmp(q,'Q2') + ...
    col_Q3 .* strcmp(q,'Q3') + col_Q4 .* strcmp(q,'Q4') + ...
    col_bnd .* strcmp(q,'boundary');

colours = cell2mat(arrayfun(@(i) quad_colour(quad(i)), (1:height(T))', ...
    'UniformOutput', false));

%% -------------------------------------------------------------------------
%  3. Build sphere surface (semi-transparent)
% -------------------------------------------------------------------------
[SX, SY, SZ] = sphere(80);

%% -------------------------------------------------------------------------
%  4. Iso-eta latitude circles
%     cos(sigma) = 1 - 1/eta  =>  sigma = arccos(1 - 1/eta)
%     Points: (cos_sigma, sin_sigma*cos(phi), sin_sigma*sin(phi))
% -------------------------------------------------------------------------
phi_circ = linspace(0, 2*pi, 361);

iso_eta_vals    = [0.5, 0.75, 1, 2, 4, 10];
iso_eta_labels  = {'0.5', '0.75', '1', '2', '4', '10'};
iso_eta_styles  = {'-', '--', '-', '--', '-', '--'};
iso_eta_colours = [...
    0.65 0.10 0.10;   % 0.5  (eta<1, competitive)
    0.70 0.35 0.15;   % 0.75
    0.30 0.30 0.30;   % 1    (parity, bold)
    0.10 0.35 0.65;   % 2
    0.05 0.20 0.55;   % 4
    0.00 0.10 0.40];  % 10
iso_eta_lw = [1.2, 0.8, 2.0, 0.8, 1.2, 0.8];

%% -------------------------------------------------------------------------
%  5. Figure layout
% -------------------------------------------------------------------------
fig = figure('Units','centimeters','Position',[2 2 22 18],'Color','w');
ax  = axes('Parent', fig);
hold(ax, 'on');

% Sphere surface (hidden from legend)
hs = surf(ax, SX, SY, SZ, ...
    'FaceAlpha', 0.06, ...
    'FaceColor', [0.85 0.90 0.95], ...
    'EdgeColor', [0.82 0.86 0.92], ...
    'EdgeAlpha', 0.12, ...
    'LineWidth', 0.3, ...
    'HandleVisibility', 'off');

%% -------------------------------------------------------------------------
%  6. Key structural lines
% -------------------------------------------------------------------------
% Independence equator: sphere_x = 0 (rho = 0 locus)
% sigma = pi/2, cos_sigma = 0
equator_x = zeros(size(phi_circ));
equator_y = cos(phi_circ);
equator_z = sin(phi_circ);
plot3(ax, equator_x, equator_y, equator_z, ...
    'Color', [0.2 0.2 0.2], 'LineWidth', 1.4, ...
    'LineStyle', '-', 'DisplayName', '\rho = 0  (regime boundary)');

% Fisher meridian: sphere_z = 0 (tau = 0, kappa = 1 locus)
% Points on the circle sz=0, sx^2+sy^2 = 1
fisher_x = cos(phi_circ);
fisher_y = sin(phi_circ);
fisher_z = zeros(size(phi_circ));
plot3(ax, fisher_x, fisher_y, fisher_z, ...
    'Color', [0.3 0.3 0.3], 'LineWidth', 0.8, ...
    'LineStyle', ':', 'DisplayName', '\kappa = 1  (Fisher line)');

%% -------------------------------------------------------------------------
%  7. Iso-eta circles
% -------------------------------------------------------------------------
iso_h = gobjects(length(iso_eta_vals), 1);
for k = 1:length(iso_eta_vals)
    c = iso_eta_vals(k);
    cos_s = 1 - 1/c;
    if abs(cos_s) >= 1, continue; end
    sin_s = sqrt(1 - cos_s^2);
    cx = cos_s * ones(size(phi_circ));
    cy = sin_s * cos(phi_circ);
    cz = sin_s * sin(phi_circ);
    iso_h(k) = plot3(ax, cx, cy, cz, ...
        'Color', iso_eta_colours(k,:), ...
        'LineWidth', iso_eta_lw(k), ...
        'LineStyle', iso_eta_styles{k}, ...
        'DisplayName', ['\eta = ' iso_eta_labels{k}]);
end

%% -------------------------------------------------------------------------
%  8. KPI scatter points
% -------------------------------------------------------------------------
% Plot unfilled circles for non-significant rho, filled for significant
marker_sz_sig   = 60;
marker_sz_insig = 30;

% Group by quadrant for legend
for qi = 1:4
    qname = sprintf('Q%d', qi);
    mask_q = strcmp(quad, qname);
    if ~any(mask_q), continue; end

    mask_sig   = mask_q & (sig_rho == 1);
    mask_insig = mask_q & (sig_rho ~= 1);
    col_q = quad_colour(qname);

    if any(mask_sig)
        scatter3(ax, sx(mask_sig), sy(mask_sig), sz(mask_sig), ...
            marker_sz_sig, repmat(col_q, sum(mask_sig), 1), ...
            'filled', 'MarkerEdgeColor', col_q.*0.7, 'LineWidth', 0.5, ...
            'DisplayName', qname);
    end
    if any(mask_insig)
        scatter3(ax, sx(mask_insig), sy(mask_insig), sz(mask_insig), ...
            marker_sz_insig, repmat(col_q, sum(mask_insig), 1), ...
            'filled', 'MarkerEdgeColor', col_q.*0.7, 'LineWidth', 0.5, ...
            'MarkerFaceAlpha', 0.4, ...
            'HandleVisibility', 'off');
    end
end

%% -------------------------------------------------------------------------
%  9. Pole marker (eta -> infinity at sphere_x=1, sigma=0)
% -------------------------------------------------------------------------
scatter3(ax, 1, 0, 0, 120, [0.1 0.1 0.1], ...
    'Marker', 'p', 'MarkerFaceColor', [1 0.9 0.2], ...
    'MarkerEdgeColor', [0.1 0.1 0.1], 'LineWidth', 1.2, ...
    'DisplayName', '\eta \rightarrow \infty  (pole)');

% Antipole (eta -> 1/2 at sphere_x=-1, sigma=pi)
scatter3(ax, -1, 0, 0, 80, [0.5 0.5 0.5], ...
    'Marker', 'd', 'MarkerFaceColor', [0.85 0.85 0.85], ...
    'MarkerEdgeColor', [0.4 0.4 0.4], 'LineWidth', 1.0, ...
    'DisplayName', '\eta = 0.5  (antipole)');

%% -------------------------------------------------------------------------
%  10. Axis labels and annotations
% -------------------------------------------------------------------------
% Axis labels at endpoints
text(ax,  1.15, 0, 0, 'pole (\rho sech\tau = 1)', ...
    'FontSize', 8, 'HorizontalAlignment', 'left', 'Color', [0.2 0.2 0.2], ...
    'Interpreter', 'tex');
text(ax, -1.18, 0, 0, 'antipole', ...
    'FontSize', 8, 'HorizontalAlignment', 'right', 'Color', [0.4 0.4 0.4]);
text(ax,  0.05, 0, 1.12, '\tau > 0  (\kappa > 1)', ...
    'FontSize', 8, 'Color', [0.3 0.3 0.3], 'Interpreter', 'tex');
text(ax,  0.05, 0, -1.12, '\tau < 0  (\kappa < 1)', ...
    'FontSize', 8, 'Color', [0.3 0.3 0.3], 'HorizontalAlignment', 'left', ...
    'Interpreter', 'tex');
text(ax, -0.05, 1.08, 0, '\rho = 0', ...
    'FontSize', 8, 'Color', [0.2 0.2 0.2], 'HorizontalAlignment', 'right', ...
    'Interpreter', 'tex');

%% -------------------------------------------------------------------------
%  11. Axes formatting
% -------------------------------------------------------------------------
axis(ax, 'equal');
axis(ax, 'off');
view(ax, 210, 14);  % viewing angle: from left-rear, slightly above
                    % shows Q3 (red, main cluster) on front-right,
                    % Q1/Q2 (blue/green) visible on left hemisphere

% Draw coordinate axes manually (thin grey) — real values only
ax_len = 1.3;
plot3(ax, [-ax_len ax_len], [0 0], [0 0], 'Color', [0.7 0.7 0.7], ...
    'LineWidth', 0.5, 'HandleVisibility', 'off');
plot3(ax, [0 0], [0 ax_len], [0 0], 'Color', [0.7 0.7 0.7], ...
    'LineWidth', 0.5, 'HandleVisibility', 'off');
plot3(ax, [0 0], [0 0], [-ax_len, ax_len], 'Color', [0.7 0.7 0.7], ...
    'LineWidth', 0.5, 'HandleVisibility', 'off');

% Light
camlight(ax, 'headlight');
lighting(ax, 'gouraud');
material(ax, 'dull');

%% -------------------------------------------------------------------------
%  12. Legend and title
% -------------------------------------------------------------------------
leg = legend(ax, 'Location', 'northwest', 'FontSize', 7.5, ...
    'Box', 'on', 'EdgeColor', [0.7 0.7 0.7], ...
    'NumColumns', 1, 'Color', [0.98 0.98 0.98]);
title(ax, {'\eta as inverse spherical chord:', ...
    '113 sports KPI studies on the unit sphere'}, ...
    'FontSize', 10, 'FontWeight', 'normal');

%% -------------------------------------------------------------------------
%  13. Side panel: sigma vs eta scatter (inset)
% -------------------------------------------------------------------------
ax2 = axes('Parent', fig, 'Position', [0.74 0.06 0.23 0.28]);
hold(ax2, 'on');
sigma_vals = T.sigma;
eta_grid   = linspace(0.4, 6, 300);
sigma_grid = acos(1 - 1./eta_grid);
plot(ax2, sigma_grid, eta_grid, 'k-', 'LineWidth', 1.4, ...
    'DisplayName', '\eta = 1/(1-\cos\sigma)');

scatter(ax2, sigma_vals, eta_vals, 25, colours, 'filled', ...
    'MarkerEdgeColor', 'none', 'MarkerFaceAlpha', 0.7);

% Clip y axis
ylim(ax2, [0 6]);
xlim(ax2, [pi/4, pi]);
xticks(ax2, [pi/4, pi/2, 3*pi/4, pi]);
xticklabels(ax2, {'\pi/4', '\pi/2', '3\pi/4', '\pi'});
xlabel(ax2, '\sigma  (angular distance)', 'FontSize', 8);
ylabel(ax2, '\eta', 'FontSize', 8);
title(ax2, '\eta = 1/(1 - cos\sigma)', 'FontSize', 8, 'FontWeight', 'normal', ...
    'Interpreter', 'tex');
grid(ax2, 'on');
ax2.GridAlpha = 0.2;
ax2.FontSize  = 7;
xline(ax2, pi/2, '--', 'Color', [0.3 0.3 0.3], 'LineWidth', 0.8);  % rho=0
yline(ax2, 1,    '--', 'Color', [0.3 0.3 0.3], 'LineWidth', 0.8);  % eta=1

%% -------------------------------------------------------------------------
%  14. Save
% -------------------------------------------------------------------------
print(fig, out_path, '-dpng', '-r200');
fprintf('Saved: %s\n', out_path);
